-- Yetkinlik listelerinden Move, JavaFX, NumPy ve statsmodels cikarildi.
--
-- Hepsi projelerde gercekten geciyordu ama duz listede Java gibi yogun
-- kullanilan yetkinliklerle esit agirlikta duruyordu (Move 7 dosya, JavaFX eski
-- ders projeleri, NumPy/statsmodels tek analiz projesi). Proje teknoloji
-- satirlarinda ve yolculuk kartindaki anlatimda kaliyorlar; orasi gecmisi
-- anlatiyor, yetkinlik iddiasi degil.
--
-- Listeler commit'li yedekten (seed) birebir yaziliyor; oge kimlikleri boylece
-- yedekle ayni kaliyor. Yayim ve taslak birlikte.
do $$
declare
  cv_skills jsonb := '[{"id": "cvskill-1", "label": {"tr": "Diller", "en": "Languages"}, "items": [{"id": "cvskill-1-i-1", "value": {"tr": "Java", "en": "Java"}}, {"id": "cvskill-1-i-2", "value": {"tr": "TypeScript", "en": "TypeScript"}}, {"id": "cvskill-1-i-3", "value": {"tr": "Python", "en": "Python"}}]}, {"id": "cvskill-2", "label": {"tr": "Backend", "en": "Backend"}, "items": [{"id": "cvskill-2-i-1", "value": {"tr": "Spring Boot", "en": "Spring Boot"}}, {"id": "cvskill-2-i-2", "value": {"tr": "REST API", "en": "REST APIs"}}, {"id": "cvskill-2-i-3", "value": {"tr": "JWT", "en": "JWT"}}, {"id": "cvskill-2-i-4", "value": {"tr": "Kafka", "en": "Kafka"}}]}, {"id": "cvskill-3", "label": {"tr": "Frontend", "en": "Frontend"}, "items": [{"id": "cvskill-3-i-1", "value": {"tr": "React", "en": "React"}}, {"id": "cvskill-3-i-2", "value": {"tr": "Next.js", "en": "Next.js"}}, {"id": "cvskill-3-i-3", "value": {"tr": "Tailwind CSS", "en": "Tailwind CSS"}}]}, {"id": "cvskill-4", "label": {"tr": "Veri ve analiz", "en": "Data & analysis"}, "items": [{"id": "cvskill-4-i-1", "value": {"tr": "pandas", "en": "pandas"}}, {"id": "cvskill-4-i-2", "value": {"tr": "Jupyter", "en": "Jupyter"}}]}, {"id": "cvskill-5", "label": {"tr": "Veritaban\u0131", "en": "Databases"}, "items": [{"id": "cvskill-5-i-1", "value": {"tr": "PostgreSQL", "en": "PostgreSQL"}}, {"id": "cvskill-5-i-2", "value": {"tr": "MySQL", "en": "MySQL"}}, {"id": "cvskill-5-i-3", "value": {"tr": "MSSQL", "en": "MSSQL"}}]}, {"id": "cvskill-6", "label": {"tr": "Ara\u00e7lar", "en": "Tools"}, "items": [{"id": "cvskill-6-i-1", "value": {"tr": "Docker", "en": "Docker"}}, {"id": "cvskill-6-i-2", "value": {"tr": "Git ve GitHub", "en": "Git & GitHub"}}, {"id": "cvskill-6-i-3", "value": {"tr": "Maven", "en": "Maven"}}]}]'::jsonb;
  home_groups jsonb := '[{"id": "sgroup-1", "label": {"tr": "Diller", "en": "Languages"}, "items": [{"id": "sgroup-1-i-1", "value": {"tr": "Java", "en": "Java"}}, {"id": "sgroup-1-i-2", "value": {"tr": "TypeScript", "en": "TypeScript"}}, {"id": "sgroup-1-i-3", "value": {"tr": "Python", "en": "Python"}}]}, {"id": "sgroup-2", "label": {"tr": "Backend", "en": "Backend"}, "items": [{"id": "sgroup-2-i-1", "value": {"tr": "Spring Boot", "en": "Spring Boot"}}, {"id": "sgroup-2-i-2", "value": {"tr": "REST API", "en": "REST APIs"}}, {"id": "sgroup-2-i-3", "value": {"tr": "JWT", "en": "JWT"}}, {"id": "sgroup-2-i-4", "value": {"tr": "Apache Kafka", "en": "Apache Kafka"}}]}, {"id": "sgroup-3", "label": {"tr": "Frontend", "en": "Frontend"}, "items": [{"id": "sgroup-3-i-1", "value": {"tr": "React", "en": "React"}}, {"id": "sgroup-3-i-2", "value": {"tr": "Next.js", "en": "Next.js"}}, {"id": "sgroup-3-i-3", "value": {"tr": "Tailwind CSS", "en": "Tailwind CSS"}}]}, {"id": "sgroup-4", "label": {"tr": "Veri ve Analiz", "en": "Data & Analysis"}, "items": [{"id": "sgroup-4-i-1", "value": {"tr": "pandas", "en": "pandas"}}, {"id": "sgroup-4-i-2", "value": {"tr": "Jupyter", "en": "Jupyter"}}]}, {"id": "sgroup-5", "label": {"tr": "Veritaban\u0131", "en": "Databases"}, "items": [{"id": "sgroup-5-i-1", "value": {"tr": "PostgreSQL", "en": "PostgreSQL"}}, {"id": "sgroup-5-i-2", "value": {"tr": "MySQL", "en": "MySQL"}}, {"id": "sgroup-5-i-3", "value": {"tr": "MSSQL", "en": "MSSQL"}}]}, {"id": "sgroup-6", "label": {"tr": "Ara\u00e7lar", "en": "Tools"}, "items": [{"id": "sgroup-6-i-1", "value": {"tr": "Docker", "en": "Docker"}}, {"id": "sgroup-6-i-2", "value": {"tr": "Git ve GitHub", "en": "Git & GitHub"}}, {"id": "sgroup-6-i-3", "value": {"tr": "Maven", "en": "Maven"}}]}]'::jsonb;
begin
  update public.content_documents set published = jsonb_set(published, '{skills}', cv_skills) where slug = 'cv';
  update public.content_drafts    set data      = jsonb_set(data,      '{skills}', cv_skills) where slug = 'cv';
  update public.content_documents set published = jsonb_set(published, '{skills,groups}', home_groups) where slug = 'home';
  update public.content_drafts    set data      = jsonb_set(data,      '{skills,groups}', home_groups) where slug = 'home';
end $$;
